# 关于模拟交易的问题。

模拟交易只有第一天成功了，第二天和第三天出现如下错误。

2016-01-27 09:20 [SYS ERROR] handle_data函数运行失败，今天无法生成信号: handle_data() internal error line 184, in handle_data IndexError: list index out of range

回测时候没有问题，为什么会这样？
我自己分析，应该是我在handle_data外部定义一个变量，然后再handle_data里使用它。
等第二天再调用handle_data时候，外部的变量被重置了。所以会出现这个问题。

如何解决？是不是得把外部的变量写道一些文件里？
望指点。