# 回测成功，为啥模拟出错，求大神指导。。。

2016-03-30 09:28 [SYS ERROR] handle_data函数运行失败，今天无法生成信号: handle_data() internal error line 25, in handle_data File "quartz_live/ext/MFHandler/SignalProcess.py", line 75, in neutralize result = handle_recv_json(r) File "quartz_live/ext/MFHandler/Exception.py", line 185, in handle_recv_json raise MFOutputError(input_dict.get('result').get('error')) MFOutputError: None

2016-03-29 19:59 [SYS INFO] 策略初始化成功

出错的行是最后一行signal_PE的：

```python
def handle_data(account):                  # 每个交易日的买入卖出指令
    
    # 获取上一个交易日
    yesterday = account.previous_date.strftime('%Y%m%d')

    # 信号获取
    # 市盈率
    PE =DataAPI.MktStockFactorsOneDayGet(tradeDate=yesterday,secID=account.universe,field=u"secID,PE",pandas="1").set_index('secID')
    PE = 1.0 / PE
    ep = PE['PE'].dropna().to_dict()
    signal_PE = pd.Series(standardize(neutralize(winsorize(ep),yesterday)))  
```

