# 分钟策略中get_daily_attribute_history接口报错

 经过测试定位，错误就在运行这句时有问题
 all_close_prices = account.get_daily_attribute_history('closePrice', 30)
 
 按照api写的看不明白错误在哪，是系统更新还没完成吗？
 
 错误如下：
 ValueError                                Traceback (most recent call last)
&lt;mercury-input-6-b84b676524db&gt; in &lt;module&gt;()
    123                                                     slippage        = slippage,
    124                                                     refresh_rate    = refresh_rate,
--&gt; 125                                                     freq            = freq)
    126         perf = quartz.perf_parse(bt, quartz_acct)
    127     elif _QUARTZ_CACHE.get('start', 0) == sim_params.first_trading_day and          _QUARTZ_CACHE.get('end', 0) == sim_params.last_trading_day and          _QUARTZ_CACHE.get('benchmark', 0) == sim_params.benchmark and          _QUARTZ_CACHE.get('universe', 0) == sim_params.universe:

python2.7/site-packages/quartz/backtest_new.pyc in backtest_generator_new(start, end, benchmark, universe, capital_base, initialize, handle_data, security_base, commission, slippage, refresh_rate, freq, *args, **kwargs)
    410             pass
    411         if len(output) == 0:
--&gt; 412             raise ValueError('Backtest report is empty, please check the date range and history window!')
    413         clear_account_instance()
    414         return output, account

ValueError: Backtest report is empty, please check the date range and history window!

