# 麻烦给看下这是啥异常，同一程序昨天还能运行

TypeError                                 Traceback (most recent call last)
&lt;mercury-input-1-12a72a77716b&gt; in &lt;module&gt;()
    194                                                     slippage        = slippage,
    195                                                     refresh_rate    = refresh_rate,
--&gt; 196                                                     freq            = freq)
    197         perf = quartz.perf_parse(bt, quartz_acct)
    198     elif _QUARTZ_CACHE.get('start', 0) == sim_params.first_trading_day and          _QUARTZ_CACHE.get('end', 0) == sim_params.last_trading_day and          _QUARTZ_CACHE.get('benchmark', 0) == sim_params.benchmark and          _QUARTZ_CACHE.get('universe', 0) == sim_params.universe:

/home/ipython/anaconda/lib/python2.7/site-packages/quartz/backtest_new.pyc in backtest_generator_new(start, end, benchmark, universe, capital_base, initialize, handle_data, security_base, commission, slippage, refresh_rate, freq, *args, **kwargs)
    334             # get minute bar data
    335             trading_days = sim_params.trading_days[i_date:i_date+5]
--&gt; 336             idxmap_ind, data_ind = data_generator_new.get_intraday_data_new(sim_params, trading_days, (idxmap_univ, data_fq))
    337 
    338             for date, minute in sorted(idxmap_ind['minb']):

/home/ipython/anaconda/lib/python2.7/site-packages/quartz/sim_condition/data_generator_new.pyc in get_intraday_data_new(sim_params, trading_days, fqfactors)
     86 
     87     idxmap_bm, data_bm = load_intraday_benchmark_data(sim_params.benchmark, trading_days)
---&gt; 88     idxmap_all, data_all = load_intraday_equity_data(sim_params.universe, trading_days)
     89 
     90     data_all = [np.array(data) for data in data_all]

/home/ipython/anaconda/lib/python2.7/site-packages/quartz/data/equity_new.pyc in load_intraday_equity_data(universe, trading_days)
    251     universe, data_all = {}, []
    252     for res in whole_info:
--&gt; 253         sub_univ, data = res.value
    254         d = len(universe)
    255         for s,v in sub_univ.items():

TypeError: 'NoneType' object is not iterable