# 发现个奇怪的问题。。。SKLEARN出错

运行回测都没问题，一加入模拟交易就这个了~~

2016-10-13 11:27 [SYS ERROR] handle_data函数运行失败，今天无法生成信号: handle_data() internal error line 71, in handle_data File "python2.7/site-packages/sklearn/ensemble/weight_boosting.py", line 600, in predict pred = self.decision_function(X) File "python2.7/site-packages/sklearn/ensemble/weight_boosting.py", line 659, in decision_function X = self._validate_X_predict(X) File "python2.7/site-packages/sklearn/ensemble/weight_boosting.py", line 261, in _validate_X_predict X = check_array(X, accept_sparse='csr', dtype=DTYPE) File "python2.7/site-packages/sklearn/utils/validation.py", line 407, in check_array context)) ValueError: Found array with 0 sample(s) (shape=(0, 630)) while a minimum of 1 is required.