# 请教一下社区的大神们，这个是什么问题？在回测里面可以运行，到了模拟盘就出现这个了

2016-10-21 13:39 [SYS ERROR] handle_data函数运行失败，今天无法生成信号: handle_data() internal error line 92, in handle_data File "python2.7/site-packages/sklearn/svm/base.py", line 150, in fit X = check_array(X, accept_sparse='csr', dtype=np.float64, order='C') File "python2.7/site-packages/sklearn/utils/validation.py", line 398, in check_array _assert_all_finite(array) File "python2.7/site-packages/sklearn/utils/validation.py", line 54, in _assert_all_finite " or a value too large for %r." % X.dtype) ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

2016-10-21 13:36 [SYS INFO] 策略初始化成功