# 求助。数据API Connection Aborted

今天总返回这样的错误，代码没有改，之前一直能跑
ConnectionError                           Traceback (most recent call last)

&lt;mercury-input-2-51E153EC0A6D4141A494A9E9DD376A99&gt; in get_factor_data(trading_day, stk_ls, factor_ls)
     45 
     46     all_field = 'secID,tradeDate,' + ','.join(factor_ls)
---&gt; 47     df = DataAPI.MktStockFactorsOneDayGet(tradeDate=trading_day,secID=stk_ls,ticker=u"",field=all_field,pandas="1")
     48 
     49     return df

/home/ipython/anaconda/lib/python2.7/site-packages/DataAPI/DATAYES.pyc in MktStockFactorsOneDayGet(tradeDate, secID, ticker, field, pandas)
   2908         for index, item in enumerate(p_list):
   2909             requestString[split_index] = ','.join(item)
-&gt; 2910             temp_result = api_base.__getCSV__(''.join(requestString), httpClient, gw=False)
   2911             if temp_result is None or len(temp_result) == 0 or temp_result[0] == '{' or (temp_result[0] == '-' and not api_base.is_no_data_warn(temp_result, False)):
   2912                 api_base.handle_error(temp_result, 104)

/home/ipython/anaconda/lib/python2.7/site-packages/DataAPI/api_base.pyc in __getCSV__(requestString, httpClient, gw)
     71         raise Exception(get_real_string('查询服务超时'))
     72     except Exception as e:
---&gt; 73         raise e
     74 
     75 def get_cache_key(frame):

ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))