# 模拟盘报错

 [SYS ERROR] handle_data函数运行失败，今天无法生成信号: handle_data() internal error line 114, in handle_data IndexError: list index out of range
 这是个什么错误？在本地用同样的日期运行没有问题啊？
 
 