# 今天无法运行策略了，都报错，大家的还好吗？

报错如下，哪位高手知道怎么处理，帮忙解答下。代码没有改，昨天还好好的。
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<mercury-input-2-5BF803183567437CB87E0C9555CA73FB> in <module>()
    251                                             accounts=accounts, preload_data=_QUARTZ_PRELOAD_DATA,
    252                                             display=True, return_quartz_data=True,
--> 253                                             threaded=quartz_createVar.get('threaded', True), need_tracking=True)
    254     _QUARTZ_CACHE['start'] = start
    255     _QUARTZ_CACHE['end'] = end

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz-3.6.0-400.egg/quartz/utils/tracking_utils.pyc in _decorator(*args, **kwargs)

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz-3.6.0-400.egg/quartz/backtest.pyc in backtest(start, end, benchmark, universe, capital_base, initialize, handle_data, post_trading_day, commission, slippage, refresh_rate, freq, security_base, security_cost, max_history_window, accounts, threaded, display, preload_data, *args, **kwargs)

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz-3.6.0-400.egg/quartz/data/data_portal.pyc in batch_load_data(self, sim_params, disabled_service, **kwargs)

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz-3.6.0-400.egg/quartz/data/market_service.pyc in batch_load_data(self, start, end, universe, calendar_service, universe_service, asset_service, **kwargs)

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz-3.6.0-400.egg/quartz/data/market_service.pyc in rolling_load_daily_data(self, trading_days, max_cache_days)

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz-3.6.0-400.egg/quartz/data/market_service.pyc in rolling_load_daily_data(self, trading_days, max_cache_days, asset_service)

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz-3.6.0-400.egg/quartz/data/market_service.pyc in _rolling_load_data(data, trading_days, universe, max_cache_days, data_load_func, fields)

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz-3.6.0-400.egg/quartz/data/market_service.pyc in _daily_data_loader(self, universe, trading_days, fields)

/home/ipython/anaconda/lib/python2.7/site-packages/mercuryq-quartz-3.6.0-400.egg/quartz/data_loader/market_loader.pyc in load_daily_equity_data(universe, trading_days, field)

/home/ipython/anaconda/lib/python2.7/site-packages/pandas/core/frame.pyc in __init__(self, data, index, columns, dtype, copy)
    222                                  dtype=dtype, copy=copy)
    223         elif isinstance(data, dict):
--> 224             mgr = self._init_dict(data, index, columns, dtype=dtype)
    225         elif isinstance(data, ma.MaskedArray):
    226             import numpy.ma.mrecords as mrecords

/home/ipython/anaconda/lib/python2.7/site-packages/pandas/core/frame.pyc in _init_dict(self, data, index, columns, dtype)
    358             arrays = [data[k] for k in keys]
    359 
--> 360         return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
    361 
    362     def _init_ndarray(self, values, index, columns, dtype=None, copy=False):

/home/ipython/anaconda/lib/python2.7/site-packages/pandas/core/frame.pyc in _arrays_to_mgr(arrays, arr_names, index, columns, dtype)
   5239     axes = [_ensure_index(columns), _ensure_index(index)]
   5240 
-> 5241     return create_block_manager_from_arrays(arrays, arr_names, axes)
   5242 
   5243 

/home/ipython/anaconda/lib/python2.7/site-packages/pandas/core/internals.pyc in create_block_manager_from_arrays(arrays, names, axes)
   4002         return mgr
   4003     except ValueError as e:
-> 4004         construction_error(len(arrays), arrays[0].shape, axes, e)
   4005 
   4006 

/home/ipython/anaconda/lib/python2.7/site-packages/pandas/core/internals.pyc in construction_error(tot_items, block_shape, axes, e)
   3964     implied = tuple(map(int, [len(ax) for ax in axes]))
   3965     if passed == implied and e is not None:
-> 3966         raise e
   3967     if block_shape[0] == 0:
   3968         raise ValueError("Empty data passed with indices specified.")

ValueError: could not broadcast input array from shape (270) into shape (264)